---
- name: apt key pour le depot dotdeb
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg

- name: ajout depot update
  apt_repository:
    repo: "deb https://packages.dotdeb.org {{ansible_lsb['codename']}} all"
    update_cache: no

- name: ajout depot update backports
  apt_repository:
    repo: "deb https://deb.debian.org/debian {{ansible_lsb['codename']}}-backports main contrib non-free"
    update_cache: no

- name: Mise à jour des packages
  apt:
    update_cache: yes
